// Maps Prisma Vehicle to the GarageVehicle shape used by components

import type { GarageVehicle } from "@/data/vehicles";

export function dbToGarageVehicle(dbv: any): GarageVehicle {
  return {
    id: dbv.id,
    brand: dbv.brand,
    model: dbv.model,
    year: dbv.year,
    fuel: dbv.fuel,
    hp: dbv.hp || 0,
    mi: dbv.mileage ? dbv.mileage.toLocaleString("en-US") : "0",
    drive: dbv.drive || undefined,
    body: dbv.body || undefined,
    trans: dbv.trans || undefined,
    color: dbv.color || "Unknown",
    reg: dbv.licensePlate || "—",
    brandColor: undefined,
    seats: dbv.seats || 5,
    doors: dbv.doors || 4,
    vin: dbv.vin || "—",
    owners: dbv.owners || 1,
    accel: dbv.accel || undefined,
    top: dbv.topSpeed || undefined,
    batt: dbv.battery || undefined,
    range: dbv.rangemi || undefined,
    cons: dbv.consumption || undefined,
    co2: dbv.co2 || undefined,
    weight: dbv.weight || undefined,
    tow: dbv.towCapacity || undefined,
    len: dbv.length || undefined,
    wid: dbv.width || undefined,
    hei: dbv.height || undefined,
    inspSt: dbv.inspectionStatus || "approved",
    insp: dbv.lastInspection || undefined,
    nextInsp: dbv.nextInspection || undefined,
    servLast: dbv.lastService || undefined,
    servNext: dbv.nextService || undefined,
    ins: dbv.insurance || undefined,
    estMil: dbv.estimatedAnnualMi || undefined,
    gar: dbv.warranties || [],
    fin: dbv.financing || undefined,
    tax: dbv.annualTax || 0,
    valP: dbv.marketValue || 0,
    valC: dbv.marketValue || 0,
    pay: dbv.parkingCost || dbv.washCost || dbv.tollCost
      ? { parking: dbv.parkingCost || 0, wash: dbv.washCost || 0, toll: dbv.tollCost || 0, total: (dbv.parkingCost || 0) + (dbv.washCost || 0) + (dbv.tollCost || 0) }
      : undefined,
    fuelActual: dbv.monthlyFuelCost || undefined,
    img: dbv.imageUrl || undefined,
    status: dbv.status || "ok",
    statusT: dbv.statusText || "All Good",
    equip: Array.isArray(dbv.equipment) ? dbv.equipment : [],
    devs: Array.isArray(dbv.deviations) ? dbv.deviations : [],
    servBook: Array.isArray(dbv.serviceBook) ? dbv.serviceBook : [],
    tyres: dbv.tires || undefined,
  };
}
